[package]
name = "sia_vbd"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec", "compat"] }
futures = "0.3"
anyhow = { version = "1.0", features = ["backtrace"] }
bytes = "1"
bitflags = "2.6"
num_enum = "0.7"
once_cell = "1.20"
byteorder = "1.5"
thiserror = "2.0"