[package]
name = "sia_vbd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
bitflags = "2.6"
bytes = "1"
compact_bytes = "0.1"
futures = "0.3"
num_enum = "0.7"
once_cell = "1.20"
thiserror = "2.0"
tokio = { version = "1.41", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec", "compat"] }